DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255) NOT NULL DEFAULT '',
  LAST_NAME VARCHAR(255) NOT NULL DEFAULT '',
  TITLE VARCHAR(255) NOT NULL DEFAULT 'EMPLOYEE',
  PHONE VARCHAR(20) NOT NULL DEFAULT '',
  HIRE_DATE DATE DEFAULT NULL,
  MANAGER BOOLEAN NOT NULL DEFAULT FALSE,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRIMARY KEY (EMPLOYEE_ID)
  );

DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR (255) NOT NULL DEFAULT '',
  DEPARTMENT_MANAGER NUMBER (10,0),
  PRIMARY KEY (DEPARTMENT_ID)
);

DROP IF EXISTS SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;